export const experienceList = [
  {
    id: 1,
    companyName: "ICETEA MEDIA ",
    period: "Feb 2023 - Present",
    position: "Frontend Web Developer",
    location: "HSR Layout, Bangalore, India",
    skills: [
      "React JS",
      "JavaScript",
      "HTML",
      "Redux",
      "Git",
      "Next.js",
      "TypeScript",
      "CSS",

      "GitHub",
      "Material UI",
      "Ant Design",
      "Tailwind CSS",
      "Figma",
      "REST API",
    ],
  },
  {
    id: 2,
    companyName: "TREATMENT TRAVELLER ",
    period: "Oct 2021 - Feb 2023 · 1 yr 6 mos",
    position: "Frontend Web Developer",
    location: "Noida, Uttar Pradesh, India",
    skills: [
      "React JS",
      "JavaScript",
      "HTML",
      "Redux",
      "Git",
      "Next.js",
      "TypeScript",
      "CSS",
      "jQuery",
      "GitHub",
      "Material UI",
      "Ant Design",
      "Tailwind CSS",
      "Figma",
      "REST API",
    ],
    logo: "/ttLogo.png",
  },
];
