export const experienceList = [
  {
    id: 1,
    companyName: "Avija Digital ",
    period: "Feb 2023 - Apr 2025 · 2 yr 3 mos",
    position: "Frontend Web Developer",
    location: "Delhi, India",
    skills: [
      "React JS",
      "JavaScript",
      "HTML",
      "Redux",
      "Git",
      "Next.js",
      "TypeScript",
      "CSS",
      "jQuery",
      "GitHub",
      "Material UI",
      "Ant Design",
      "Tailwind CSS",
      "Figma",
      "REST API",
    ],
    logo: "/ttLogo.png",
  },

  {
    id: 2,
    companyName: "ICETEA MEDIA ",
    period: "Apr 2021 - Feb 2023 : 1 yr 11 mos ",
    position: "Frontend Web Developer",
    location: "HSR Layout, Bangalore, India",
    skills: [
      "React JS",
      "JavaScript",
      "HTML",
      "Redux",
      "Git",
      "Next.js",
      "TypeScript",
      "CSS",

      "GitHub",
      "Material UI",
      "Ant Design",
      "Tailwind CSS",
      "Figma",
      "REST API",
    ],
  },
];
