export const experienceList = [
  {
    id: 1,
    companyName: "Avija Digital ",
    period: "Nov 2023 - May 2025 · 1 yr 7 mos",
    position: "Frontend Web Developer",
    location: "Delhi, India",
    skills: [
      "React JS",
      "JavaScript",
      "HTML",
      "Redux",
      "Git",
      "Next.js",
      "TypeScript",
      "CSS",
      "jQuery",
      "GitHub",
      "Material UI",
      "Ant Design",
      "Tailwind CSS",
      "Figma",
      "REST API",
    ],
    logo: "/ttLogo.png",
  },

  {
    id: 2,
    companyName: "ICETEA MEDIA ",
    period: "Nov 2022 - Oct 2023 : 1 yr 0 mos ",
    position: "Frontend Web Developer",
    location: "HSR Layout, Bangalore, India",
    skills: [
      "React JS",
      "JavaScript",
      "HTML",
      "Redux",
      "Git",
      "Next.js",
      "TypeScript",
      "CSS",

      "GitHub",
      "Material UI",
      "Ant Design",
      "Tailwind CSS",
      "Figma",
      "REST API",
    ],
  },
];
